service: sls-image-cdn-${env:SOURCE_S3_BUCKET_NAME}

plugins:
  - serverless-webpack
  - create-s3-bucket-redirect
  - serverless-offline

custom:
  webpack: webpack.config.js
  webpackIncludeModules: true
  default:
    stage: dev
    region: eu-west-1
    bucketName: ${self:service}

provider:
  name: aws
  stage: ${opt:stage, self:custom.default.stage}
  runtime: nodejs6.10
  region: ${opt:region, self:custom.default.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "*"
  environment:
    SOURCE_S3_BUCKET_NAME: ${env:SOURCE_S3_BUCKET_NAME}
    SOURCE_S3_WEBSITE: ${env:SOURCE_S3_WEBSITE, ''}

functions:
  resizer:
    handler: index.resizer
    events:
      - http:
          path: resizer/{path+}
          method: get

resources:
  Resources:
    SourceImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:SOURCE_S3_BUCKET_NAME}
        AccessControl: PublicRead
